### ISSUE TITLE
Can't install if SELinux is disabled

### ISSUE THREAD

**Issue by ananace** [voxpupuli/puppet-misp#33]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3
- Ruby: 2.4.4p296
- Distribution: CentOS 7.5.1804
- Module version: 0.5.0

## How to reproduce (e.g Puppet code you use)

```puppet
include ::misp
```

## What are you seeing 

A failure to run the 'setsebool redis' exec, and therefore failing to finish the setup of MISP.

## What behaviour did you expect instead

The service to install and configure correctly.

## Output log

```
Notice: /Stage[main]/Misp::Config/Exec[setsebool redis]/returns: setsebool:  SELinux is disabled.
Error: '/usr/sbin/setsebool -P httpd_can_network_connect on' returned 1 instead of one of [0]
Error: /Stage[main]/Misp::Config/Exec[setsebool redis]/returns: change from 'notrun' to ['0'] failed: '/usr/sbin/setsebool -P httpd_can_network_connect on' returned 1 instead of one of [0]
Notice: /Stage[main]/Misp::Service/Service[rh-php56-php-fpm]: Dependency Exec[setsebool redis] has failures: true
Warning: /Stage[main]/Misp::Service/Service[rh-php56-php-fpm]: Skipping because of failed dependencies
Notice: /Stage[main]/Misp::Service/Service[haveged]: Dependency Exec[setsebool redis] has failures: true
Warning: /Stage[main]/Misp::Service/Service[haveged]: Skipping because of failed dependencies
Notice: /Stage[main]/Misp::Service/Exec[start bg workers]: Dependency Exec[setsebool redis] has failures: true
Warning: /Stage[main]/Misp::Service/Exec[start bg workers]: Skipping because of failed dependencies
Notice: /Stage[main]/Misp::Service/Exec[restart bg workers]: Dependency Exec[setsebool redis] has failures: true
Warning: /Stage[main]/Misp::Service/Exec[restart bg workers]: Skipping because of failed dependencies
```

## Any additional information you'd like to impart

It should probably only try to run if `$facts['os']['selinux']['enabled']`/`$facts['selinux']` is true.  
Or if `selinuxenabled` exits with code 0, though that seems like a slightly hackier solution.

**Comment by bastelfreak** [comment]
the selinux config should not be handled by exec resources but rather with https://forge.puppet.com/puppet/selinux and https://puppet.com/docs/puppet/5.5/type.html#selmodule and https://puppet.com/docs/puppet/5.5/type.html#selboolean. Can you provide a PR for this @ananace ?
