### ISSUE TITLE
PHP 5.6 SCL has been end of life since April 2018, PHP itself since December 2018

### ISSUE THREAD

**Issue by ananace** [voxpupuli/puppet-misp#45]
The SCL for PHP 5.6 has been gone from the internet for a while now, making it impossible to use this module to install MISP on any system due to the lack of PHP 5.6 packages.

As MISP requires a PHP version at least 5.6 or higher, it's not supported to use the shipped PHP version in RHEL/CentOS either. (5.4.16 at the time of writing)  
Perhaps it's time to switch to a newer MISP tag and use the PHP 7.1 SCL instead, as that's what the modern documentation suggests for installing it.

**Comment by bastelfreak** [comment]
hey @ananace, thanks for bringing this up. Are you able to provide a PR for this?

**Comment by ananace** [comment]
Currently working on exactly that, though I also ended up going through and cleaning up parameters and configuration handling as I had to update MISP and Python at the same time which broke a few things.

I'll hopefully have a PR available for the latest MISP, PHP 7.1, and Python 3.6 (the recommended versions in their current install guides) in a day or two.

**Comment by ananace** [comment]
I've finished my work to the point where I'm able to spin up a full MISP instance on PHP 7.2 and Python 3.6 now, would you like a PR with all the WIP commits as well, or do you want me to rebase it down to a more reasonable amount? :smiley:

**Comment by bastelfreak** [comment]
a reasonable amount probably makes reviews easier and we can merge it faster :)

**Comment by ananace** [comment]
I'll try to split my work in two PRs, one to move to newer PHP, and one to update the configuration and parameter handling - as that's mainly for my own sanity.

Going to see if I can reduce some of the noise I'm getting on the MISP server beforehand though, it's applying "changes" almost every run
