### ISSUE TITLE
Workflow in this module

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-misp#6]
Hi,

On Vox Pupuli we work with the github-workflow, or Pull Requests. This means: You fork the module, create a feature/bugfix branch, make your changes, push it to your fork, create a pull request, somebody reviews it and then it gets merged into master. We don't directly push to master. And we try to not create feature/bugfix branches in the Vox Pupuli namespace.

----

I disabled direct pushes to master in this repository. If you've any questions feel free to respond here or join our IRC channel #voxpupuli on freenode.

**Comment by ppanero** [comment]
Hello @bastelfreak 

Done. Im really sorry will not happen again. You are right that this is not the proper way. I already changed.

Cheers,
Pablo

**Comment by bastelfreak** [comment]
Alrighty. Let us know if you've any additional questions.
