### ISSUE TITLE
Failed to install crypt GPG

### ISSUE THREAD

**Issue by ppanero** [voxpupuli/puppet-misp#9]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby:
- Distribution: CentOS
- Module version: 0.2.2

## How to reproduce (e.g Puppet code you use)
Run puppet with no dependencies already installed
## What are you seeing
Failed to install php-pear-crypt-gpg
## What behaviour did you expect instead
the package being installed
## Output log
```
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install php-pear-Crypt-GPG' returned 1: Error: Nothing to do
Error: /Stage[main]/Misp::Dependencies/Package[php-pear-Crypt-GPG]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install php-pear-Crypt-GPG' returned 1: Error: Nothing to do
```
## Any additional information you'd like to impart
It is sensitive to lower/capital letters

**Comment by ppanero** [comment]
Solved

**Comment by kaileena1** [comment]
how did you solve it?
